/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.rodez.demo;

/**
 * The {@code FizzBuzz} class represents a simple program that plays the
 * FizzBuzz game. It provides a method to determine the FizzBuzz output for a
 * given number.
 *
 * <p>FizzBuzz is a popular programming interview question that requires
 * printing the numbers from 1 to 100. For multiples of 3, print "Fizz" instead
 * of the number. For multiples of 5, print "Buzz" instead of the number. For
 * numbers which are multiples of both three and five, print "FizzBuzz".
 * Otherwise, print the number itself.
 *
 * <p>This class is designed to demonstrate a basic implementation of the
 * FizzBuzz algorithm.
 *
 * @author <your name>
 * @version 1.0
 */
public class FizzBuzz {

  /**
   * Plays the FizzBuzz game for a given number and returns the corresponding
   * output.
   *
   * @param number The input number for the FizzBuzz game.
   * @return The FizzBuzz output as a String.
   * @throws IllegalArgumentException If the input number is less than 0.
   */
  public String play(int number) throws IllegalArgumentException{
    if(number < 0)
      throw new IllegalArgumentException("CKC");
    if(number % 3 == 0){
      if(number % 5 == 0)
        return "FizzBuzz";
      return "Fizz"; }
      if(number % 5 == 0)
      return "Buzz";
    return Integer.toString(number);
  }
}
