/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.rodez.demo;

/**
 * The {@code FizzBuzz} class represents a simple program that plays the
 * FizzBuzz game. It provides a method to determine the FizzBuzz output for a
 * given number.
 *
 * <p>FizzBuzz is a popular programming interview question that requires
 * printing the numbers from 1 to 100. For multiples of 3, print "Fizz" instead
 * of the number. For multiples of 5, print "Buzz" instead of the number. For
 * numbers which are multiples of both three and five, print "FizzBuzz".
 * Otherwise, print the number itself.
 *
 * <p>This class is designed to demonstrate a basic implementation of the
 * FizzBuzz algorithm.
 *
 * @author Fabien ESCOURBIAC
 * @version 1.0
 */
public class FizzBuzz {
  /**
   * Number that must be replaced by Fizz.
   */
  private static final int FIZZ_NUMBER = 3;
  /**
   * Number that must be replaced by Buzz.
   */
  private static final int BUZZ_NUMBER = 5;

  /**
   * Plays the FizzBuzz game for a given number and returns the corresponding
   * output.
   *
   * @param number The input number for the FizzBuzz game.
   * @return The FizzBuzz output as a String.
   * @throws IllegalArgumentException If the input number is less than 1.
   */
  public String play(int number) {
    if (number < 1) {
      throw new IllegalArgumentException("Input number must be greater than or equal to 1.");
    }

    if (MathUtils.isDivisibleBy(number, FIZZ_NUMBER)
        && MathUtils.isDivisibleBy(number, BUZZ_NUMBER)) {
      return "FizzBuzz";
    } else if (MathUtils.isDivisibleBy(number, FIZZ_NUMBER)) {
      return "Fizz";
    } else if (MathUtils.isDivisibleBy(number, BUZZ_NUMBER)) {
      return "Buzz";
    } else {
      return String.valueOf(number);
    }
  }
}
